service:
  type: ClusterIP  # or LoadBalancer, NodePort, etc.

mode: standalone  # Options: standalone, cluster

replicaCount: 2

image:
  repository: postgres
  tag: "13"
  pullPolicy: IfNotPresent

postgresql:
  database: mydatabase
  username: myuser
  generatePassword: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: true

ingress:
  enabled: false

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: standard
