apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  mode: daemonset
  hostNetwork: true
  config: |
    receivers:
      otlp:
        protocols:
          grpc: {}
    processors: {}
    exporters:
        debug: {}
        otlp:
            endpoint: tempo:4317
            tls:
                insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug, otlp]