apiVersion: v2
name: microservice
description: A Helm chart for a microservice in Kubernetes
type: application
version: 0.1.2
appVersion: "0.1.2"
maintainers:
  - name: Ashwani Singh
    email: ashwani.singh@opstree.com
  - name: Shikha Tripathi
