replicaCount: 1

fullnameOverride: "nginx"
nameOverride: ""
image:
  repository: nginx # your microservice image name 
  pullPolicy: IfNotPresent
  tag: "latest"     # your microservice image tag

service:
  type: ClusterIP
  port: 80
