apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-helm.name" . }}-secret
  labels:
    {{- include "postgresql-helm.labels" . | nindent 4 }}
data:
  postgresql-password: {{ randAlphaNum 16 | b64enc }}
