apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgresql-helm.fullname" . }}
  labels:
    {{- include "postgresql-helm.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "postgresql-helm.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "postgresql-helm.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "postgresql-helm.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql-helm.fullname" . }}-secret
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "postgresql-helm.labels" . | nindent 8 }}
      spec:
        accessModes: [ "{{ .Values.persistence.accessMode }}" ]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
