apiVersion: v2
name: tempo-standalone
description: A Helm chart for standalone tempo setup
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: tempo
    version: ~1
    repository: https://grafana.github.io/helm-charts
    alias: tempo
    tags:
      - logging
    condition: tempo.enabled

  - name: opentelemetry-operator
    version: ~0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    tags:
      - logging
    alias: otel-operator
    condition: otel-operator.enabled