tempo:
  enabled: true

otel-operator:
  enabled: true
  manager:
    collectorImage:
      repository: otel/opentelemetry-collector-k8s
  admissionWebhooks:
    certManager:
      enabled: false
    autoGenerateCert:
      enabled: true