apiVersion: v2
name: pxc-operator
description: A Helm chart for percona xtradb operator
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: pxc-operator
    version: ~1
    repository: https://percona.github.io/percona-helm-charts/
    alias: pxc-operator
    tags:
      - pxc-operator
    condition: pxc-operator.enabled