apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservice.fullname" . }}
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.secret.key }}: {{ .Values.secret.value | b64enc }}
